# Generated by Django 4.1 on 2022-09-23 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Name not valid: name must start and ends with letter and can contain only ' ' or '-' special characters ", regex='^[a-zA-Z][a-zA-Z\\-\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message="Name not valid: name must start and ends with letter and can contain only ' ' or '-' special characters ", regex='^[a-zA-Z][a-zA-Z\\-\\s]*$')]),
        ),
    ]
