# Generated by Django 4.1 on 2022-09-20 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatar', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Avatar'),
        ),
    ]
