# Generated by Django 4.1 on 2022-09-09 11:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256, unique=True, validators=[django.core.validators.EmailValidator(code='Invalid email', message='Please provide valid email address')], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z\\-\\s]*', message="Name not valid: name must start and ends with letter and can contain \n                only ' ' or '-' special characters ")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z\\-\\s]*', message="Name not valid: name must start and ends with letter and can contain \n                only ' ' or '-' special characters ")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z\\d!@#$&*][a-zA-Z\\d!@#$&*]{8,64}$')]),
        ),
    ]
