# Generated by Django 4.1 on 2022-09-09 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z\\-\\s]*', message="Name not valid: name must start and ends with letter and can contain only ' ' or '-' special characters ")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z\\-\\s]*', message="Name not valid: name must start and ends with letter and can contain only ' ' or '-' special characters ")]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must be beetween 8-64 characters and can include Upper/lower cases, digits and special characters', regex='^.{8,64}$')]),
        ),
    ]
