# Generated by Django 4.1 on 2022-10-06 12:14

import MusicHub.tracks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(MusicHub.tracks.models.get_sentinal_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
