# Generated by Django 4.1 on 2022-09-23 11:01

import MusicHub.tracks.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track',
            field=models.FileField(upload_to=MusicHub.tracks.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav', 'aac'])]),
        ),
    ]
