# Generated by Django 4.1 on 2022-10-13 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0002_playlist_created_at_playlist_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='likes',
        ),
        migrations.AddField(
            model_name='playlist',
            name='likes',
            field=models.ManyToManyField(related_name='playlist_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
